name: UltimateParticles
main: UltimateParticles\UltimateParticles
api: [3.3.4]
version: 4.2.1
load: POSTWORLD
author: Klaus

commands:
  ultimateparticles:
    usage: /ultimateparticles help
    permission: ultimateparticles.command
    description: Main command of UltimateParticles (Non-WalkingParticles stuff)
    aliases: ["ultip"]
    
permissions:
  ultimateparticles.command:
    default: op
    children:
      ultimateparticles.command.help:
        default: op
      ultimateparticles.command.ejector:
        default: op
